### ISSUE TITLE
Update to v1.24-Update3

### ISSUE THREAD

**Issue by audreytoskin** [kendaleiv/chocolatey-veracrypt#10]
There were [a couple updates in December](https://www.veracrypt.fr/en/Release%20Notes.html) -- Update2 especially fixes an annoying issue I've been having with multiboot.

Thanks :)

**Comment by audreytoskin** [comment]
...Oh, I see from the commits here you actually have pending changes for Update2 already. If it wouldn't add much delay, then it might make sense to skip to Update3. Though if it _would_ add more time, then going ahead and pushing Update2 anyway is what fixes my particular problem right now...

Thanks either way.

**Comment by kendaleiv** [comment]
The latest Windows version is `1.24-Update2`. Linux and FreeBSD are at `1.24-Update3`. So, looks like there's nothing to do, at least for now. Thanks for checking into it though!
