### ISSUE TITLE
Hang during update

### ISSUE THREAD

**Issue by jmcker** [kendaleiv/chocolatey-veracrypt#11]
The installer required manual intervention at:

![image](https://user-images.githubusercontent.com/25001741/72173472-a2130f80-33a5-11ea-85c7-55ff6a39859f.png)

while upgrading from v1.23.2 to v1.24.20191216.

This may be intentional, but just wanted to check!

**Comment by kendaleiv** [comment]
Manual intervention is not intensional. Does it happen consistently by chance? Does uninstalling and reinstalling have the same issue?

**Comment by jmcker** [comment]
I tried it again on a different system and the upgrade from v1.23.2 to v1.24.20191216 went smoothly. Must be intermittent or something I did while upgrading the first time; I'm guessing it was the latter. I'll reopen if I run into it again. Thanks!
