### ISSUE TITLE
Update to v.1.24-Update6

### ISSUE THREAD

**Issue by TyPh00nCdr** [kendaleiv/chocolatey-veracrypt#13]
VeraCrypt v.1.24-Update6 was released for Windows on March 10, 2020. Please update your scripts accordingly.
- [[official download page](https://www.veracrypt.fr/en/Downloads.html)]
- [[direct download](https://launchpad.net/veracrypt/trunk/1.24-update6/+download/VeraCrypt%20Setup%201.24-Update6.exe)]
- [[changelog](https://www.veracrypt.fr/en/Release%20Notes.html)]

Thank you!

**Comment by kendaleiv** [comment]
Thanks! Published as https://chocolatey.org/packages/veracrypt/1.24.20200419.

**Comment by TyPh00nCdr** [comment]
So this has been pending _automated_ review for five days now. From your experience, when do you think it might go live?

**Comment by kendaleiv** [comment]
Resubmitted it before and then again this evening and this time it was approved.
