### ISSUE TITLE
Update to VeraCrypt 1.24-Update7

### ISSUE THREAD

**Issue by CypherNL** [kendaleiv/chocolatey-veracrypt#14]
VeraCrypt 1.24-Update7 has been released on Friday August 7, 2020 (~5 days ago of this issue).

This is an reminder to request an package update to the version above.

Tags page and see the age of the newest update:
https://www.veracrypt.fr/code/VeraCrypt/

Download page:
https://www.veracrypt.fr/en/Downloads.html

Changelog:
https://www.veracrypt.fr/en/Release%20Notes.html

**Comment by kendaleiv** [comment]
Thanks for the notification! Published as https://chocolatey.org/packages/veracrypt/1.24.20200814.
