### ISSUE TITLE
Update to v.1.24

### ISSUE THREAD

**Issue by TyPh00nCdr** [kendaleiv/chocolatey-veracrypt#7]
VeraCrypt v.1.24 was released on October 6, 2019. Please update your scripts accordingly.

- [[official download page](https://www.veracrypt.fr/en/Downloads.html)]
- [[direct download](https://launchpad.net/veracrypt/trunk/1.24/+download/VeraCrypt%20Setup%201.24.exe)]
- [[changelog](https://www.veracrypt.fr/en/Release%20Notes.html)]

**Comment by kendaleiv** [comment]
Thanks! Published as https://chocolatey.org/packages/veracrypt/1.24.
